version: "3"

services:
  postgres:
    image: postgres:13.7-alpine
    container_name: pg
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=super_secret
      - POSTGRES_DB=pg_base
    restart: always
    ports:
      - "5432:5432"
    networks:
      auto:
        ipv4_address: 172.172.175.2

networks:
  auto:
    ipam:
      driver: default
      config:
        - subnet: "172.172.175.0/24"
